### PR TITLE
Use values if there are multiple tables in same page

### PR DESCRIPTION
**Pull request by mohithg**

### CODE REVIEW

**Comment by mohithg** [comment]
Scenario which fails:
If there are multiple tables in same page then we cache with row and col numbers which will be same for both tables. So this will cause issue.

After Fix:
Now the users can pass `value: instance.guid` if required or any custom values either may be an array or object which we can cache with, so even if the value has changed it will be useful.

**Comment by zekedroid** [comment]
Good catch! While I review the commit, does the scenario you mention fail even if you create two instances of the cache? It's not in the docs, but ideally you would create one cache per table so as to avoid complexity in this code base.

**Comment by mohithg** [comment]
Maintaining two instances solves the problem of having multiple tables in page but there is another problem I found.

Problem:
Lets say we have a react-renderer in column 0 and a normal text renderer in column 1, and when something change in column 1, the rowData change and something needs to change in column 0, since we are caching by row number and column 0, our cache returns the memoized container than computing the new one since the value has changed?

I think to tackle this problem we surely need to depend on value where value is `data`

Thoughts?

**Comment by zekedroid** [comment]
Glad to hear the two instances approach works. 

Let's see, about that second case, I'm not sure I understand. The idea is that the containers themselves are cached, not the content within it. Think of it more like the HTML DOM elements themselves are cached, the ones that will host the React root nodes. After that, any change to the data will be reflected in the React component, regardless of the cache. The only difference is that when you use this approach it will ensure you are never remounting components but rather sending updates to already mounted ones.

In your example, when the `rowData` changes, the new data is going to be passed to the column 0 renderer (the react-lru renderer) and while the container itself will be cached, the mounted component will be updated. Does that make sense?

**Comment by mohithg** [comment]
Hmm, that makes sense, thanks!

But when I use handsontable with fixedLeftColumns, and I am using react-lru for those columns then the .ht_master is just displaying empty <td> (not mounting the React-Component) but the .ht_clone_left table shows the component. Can you see why this is happening?

**Comment by zekedroid** [comment]
Ah, now that is a bug. Let me take a look and see what's going on. And thanks for all the input, I hope the library will help you out in the future!

**Comment by zekedroid** [comment]
Closing PR. Will not implement over existing functionality.

**Pull request closed without merging**
